name: example
description: Example of zero-dce implementation on cross platform app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# major.minor.patch+yymm__dd
version: 0.0.1+21120000

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Internationalization & Localizations
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  magnific_ui: ^0.2.1
  magnific_core: ^0.1.2
  app_boot: ^0.1.0
  riverpod: ^1.0.0
  flutter_riverpod: ^1.0.0
  dio: ^4.0.4
  freezed_annotation: ^1.0.0
  shared_preferences: ^2.0.9
  retrofit: ^3.0.0
  intl: ^0.17.0
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.0
  navigator: ^0.2.1+1
  # Firebase suite
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_analytics: ^9.0.2

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.0.0
  # for l10n synthetic deps generation
  flutter_gen_runner: ^4.0.0
  retrofit_generator: ^3.0.0+2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - google_fonts/
    - assets/anim/
