// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqZ9Mjptf9_2C-UYCQ65wMKiUGGksM9k',
    appId: '1:721345063370:web:7bfd29e04e8716c9ee8733',
    messagingSenderId: '721345063370',
    projectId: 'flutter-template-93827',
    authDomain: 'flutter-template-93827.firebaseapp.com',
    storageBucket: 'flutter-template-93827.appspot.com',
    measurementId: 'G-5B6L714QD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwwiITOS5YZA61eGY4Huco0hYEMOvoyIM',
    appId: '1:721345063370:android:aa1a1c332d6770fcee8733',
    messagingSenderId: '721345063370',
    projectId: 'flutter-template-93827',
    storageBucket: 'flutter-template-93827.appspot.com',
  );
}
